// <auto-generated />
using System;
using CaoLendario.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CaoLendario.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CaoLendario.Models.Animal", b =>
                {
                    b.Property<int>("AnimalID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("GostaBrincar")
                        .HasColumnType("bit");

                    b.Property<string>("HistoricoVida")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Nascimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("NomeAnimal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Peso")
                        .HasColumnType("float");

                    b.Property<int>("Porte")
                        .HasColumnType("int");

                    b.Property<bool>("PossuiDeficiencia")
                        .HasColumnType("bit");

                    b.Property<bool>("RelacionaGato")
                        .HasColumnType("bit");

                    b.Property<bool>("RelacionaOutroCao")
                        .HasColumnType("bit");

                    b.Property<int>("Sexo")
                        .HasColumnType("int");

                    b.Property<string>("Temperamento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoPelagem")
                        .HasColumnType("int");

                    b.Property<string>("UrlFoto")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AnimalID");

                    b.ToTable("Animais");
                });

            modelBuilder.Entity("CaoLendario.Models.Interesse", b =>
                {
                    b.Property<int>("InteresseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Adotado")
                        .HasColumnType("bit");

                    b.Property<int>("AdotanteID")
                        .HasColumnType("int");

                    b.Property<int>("AnimalID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.HasKey("InteresseID");

                    b.HasIndex("AdotanteID");

                    b.HasIndex("AnimalID");

                    b.ToTable("Interesse");
                });

            modelBuilder.Entity("CaoLendario.Models.ProcedimentosPosAdocao", b =>
                {
                    b.Property<int>("ProcedimentosPosAdocaoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AnimalID")
                        .HasColumnType("int");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.Property<DateTime>("data")
                        .HasColumnType("datetime2");

                    b.Property<string>("descricao")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProcedimentosPosAdocaoID");

                    b.HasIndex("AnimalID");

                    b.HasIndex("UserID");

                    b.ToTable("ProcedimentosPosAdocao");
                });

            modelBuilder.Entity("CaoLendario.Models.ProcedimentosPreAdocao", b =>
                {
                    b.Property<int>("ProcedimentosPreAdocaoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AnimalID")
                        .HasColumnType("int");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.Property<DateTime>("data")
                        .HasColumnType("datetime2");

                    b.Property<string>("descricao")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProcedimentosPreAdocaoID");

                    b.HasIndex("AnimalID");

                    b.HasIndex("UserID");

                    b.ToTable("ProcedimentosPreAdocao");
                });

            modelBuilder.Entity("CaoLendario.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cep")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("data_nascimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("endereco")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("senha")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("telefone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("uf")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserID");

                    b.ToTable("Users");

                    b.HasDiscriminator<string>("Discriminator").HasValue("User");
                });

            modelBuilder.Entity("CaoLendario.Models.Adotante", b =>
                {
                    b.HasBaseType("CaoLendario.Models.User");

                    b.Property<int>("castrado")
                        .HasColumnType("int");

                    b.Property<int>("filhote")
                        .HasColumnType("int");

                    b.Property<int>("moradia")
                        .HasColumnType("int");

                    b.Property<int>("porte")
                        .HasColumnType("int");

                    b.Property<int>("sexo")
                        .HasColumnType("int");

                    b.Property<int>("talimentacao")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Adotante");
                });

            modelBuilder.Entity("CaoLendario.Models.MedicoVeterinario", b =>
                {
                    b.HasBaseType("CaoLendario.Models.User");

                    b.Property<string>("CRMV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.HasDiscriminator().HasValue("MedicoVeterinario");
                });

            modelBuilder.Entity("CaoLendario.Models.Interesse", b =>
                {
                    b.HasOne("CaoLendario.Models.Adotante", "Adotante")
                        .WithMany()
                        .HasForeignKey("AdotanteID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CaoLendario.Models.Animal", "Animal")
                        .WithMany("Interesse")
                        .HasForeignKey("AnimalID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CaoLendario.Models.ProcedimentosPosAdocao", b =>
                {
                    b.HasOne("CaoLendario.Models.Animal", "Animal")
                        .WithMany("ProcedimentosPosAdocao")
                        .HasForeignKey("AnimalID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CaoLendario.Models.User", null)
                        .WithMany("posadocao")
                        .HasForeignKey("UserID");
                });

            modelBuilder.Entity("CaoLendario.Models.ProcedimentosPreAdocao", b =>
                {
                    b.HasOne("CaoLendario.Models.Animal", "Animal")
                        .WithMany("ProcedimentosPreAdocao")
                        .HasForeignKey("AnimalID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CaoLendario.Models.User", null)
                        .WithMany("preadocao")
                        .HasForeignKey("UserID");
                });
#pragma warning restore 612, 618
        }
    }
}
